apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerwebapi-deployment
  labels:
    app: dockerwebapi
spec:
  selector:
    matchLabels:
      app: dockerwebapi
  template:
    metadata:
      labels:
        app: dockerwebapi
    spec:
      containers:
      - name: dockerwebapi
        image: venkatakrishna09102022.azurecr.io/docwebapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionStrings__DatabaseConnectionString
            value: Server=testdbserver121.database.windows.net;Database=testweb;User Id=venkatakrishna;Password=Second@123;
---
apiVersion: v1
kind: Service
metadata:
  name: dockerwebapi-service
spec:
  type: NodePort
  selector:
    app: dockerwebapi
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31000

